### ISSUE TITLE
Cant sign in after workos upgrade .

### ISSUE THREAD

**Issue by apoorv-2204** [workos/workos-elixir#32]
Cant find to change log.

After upgrading my workos from  {:workos, "~> 0.1.2"} to {:workos, "~> 0.3.0"}, post gmail login it says authentication failure. 
There were no major change in code.

**Comment by cmatheson** [comment]
Hi @apoorv-2204, could you please message support@workos.com with more details about what's going wrong? (Please include any information that will help troubleshoot like your `organization_id`).
