### ISSUE TITLE
Make Hackney an optional dependency

### ISSUE THREAD

**Issue by BlueHotDog** [workos/workos-elixir#6]
Hey,
Seems like Hackney/Jason can/should be optional as one should be able to provide his own such libs(we're using Mint for example).
Also, while making it, might be nice to use same trick as here:
https://github.com/absinthe-graphql/dataloader/blob/cc497d91137bb1360ae6d4e0593478cbdee766fe/lib/dataloader/ecto.ex

**Comment by BlueHotDog** [comment]
The added benefit for this is not forcing to release workos-elixir for each hackney release(but let users handle their own as they need)

**Comment by LauraBeatris** [comment]
Hey @BlueHotDog, thanks for raising that!

I'm addressing this as an improvement to be related to the upcoming major version https://github.com/workos/workos-elixir/pull/36

**Comment by LauraBeatris** [comment]
Already implemented as part of 1.0.0 major version release https://github.com/workos/workos-elixir/pull/37. Thanks for raising that @BlueHotDog!

**Comment by LauraBeatris** [comment]
Already implemented as part of 1.0.0 major version release https://github.com/workos/workos-elixir/pull/37. Thanks for raising that @BlueHotDog!
